### ISSUE TITLE
Issue while Pre-training the model

### ISSUE THREAD

**Issue by mirishkarganesh** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#11]
Hi Guys,

Can you please help me out in solving this issue, I am training for pretraining

Following is the error which I have encountered

```

** Directory to code is: /2expasr/ganesh/new_exps/asr/mywtov
** Config path is: /2expasr/ganesh/new_exps/asr/mywtov/config/pretraining//wav2vec2_base_iitm_hindi_pre.yaml
** Data path is: /2expasr/ganesh/new_exps/asr/mywtov/data/pretraining
** Checkpoint will be saved at: /2expasr/ganesh/new_exps/asr/mywtov/checkpoints/pretraining
** Logs will be saved at: /2expasr/ganesh/new_exps/asr/mywtov/logs/pretraining
** Update frequency is: 10Traceback (most recent call last):
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 513, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 613, in update
    root.__setattr__(last_key, value)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 285, in __setattr__
    raise e
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 282, in __setattr__
    self.__set_impl(key, value)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 266, in __set_impl
    self._set_item_impl(key, value)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 398, in _set_item_impl
    self._validate_set(key, value)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 143, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 176, in _validate_set_merge_impl
    target = self._get_node(key)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 136, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'data' is not in struct
	full_key: task.data
	reference_type=Any
	object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/asr/anaconda3/envs/w2v/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/opt/wav2vec/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 104, in run
    run_mode=RunMode.RUN,
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/home/asr/anaconda3/envs/w2v/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 518, in _apply_overrides_to_config
    ) from ex
hydra.errors.ConfigCompositionException: Could not override 'task.data'.
To append to your config use +task.data=/2expasr/ganesh/new_exps/asr/mywtov/data/pretraining
```

**Comment by harveenchadha** [comment]
Please can you provide the complete config you are using for pretraining?

**Comment by mirishkarganesh** [comment]
Hi @harveenchadha  Following are my config details
```
# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 1
  #seed: 2021
  wandb_project: 'IITM-hindi-PRETRAINING'

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  reset_optimizer: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: 10000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 2
  ddp_backend: legacy_ddp
  #ddp_backend: fully_sharded

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  max_update: 400000
  lr: [0.0005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768

```

**Comment by harveenchadha** [comment]
Ganesh,
Can you try updating data in the config itself.
```
task:
  _name: audio_pretraining
  data: '/2expasr/ganesh/new_exps/asr/mywtov/data/pretraining'
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false
```

and delete line 

'task.data=${data_path}' from start_pretraining.sh

**Comment by mirishkarganesh** [comment]
Thank you @harveenchadha it's working. I made the changes which you have asked me to do.
Finally, it is working.!
