### ISSUE TITLE
Error on custom data prepare_data.sh

### ISSUE THREAD

**Issue by mirishkarganesh** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#23]
Hi  Guys,

Can you please help out with issue.

```
python ../../utils/prep_scripts/manifest.py /hdd2/ganesh/my_w2v/exp_database/ul_si_cln_train --dest ../../data/finetuning --ext wav --train-name "train"  --valid-percent 0.1 --jobs -1
4336it [00:04, 3893.88it/s]joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "../../utils/prep_scripts/manifest.py", line 52, in read_file
    assert soundfile.info(fname).samplerate == 16000
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../utils/prep_scripts/manifest.py", line 102, in <module>
    main(args)
  File "../../utils/prep_scripts/manifest.py", line 72, in main
    local_arr.extend(Parallel(n_jobs = args.jobs)( delayed(read_file)(fname, args, dir_path) for fname in tqdm(glob.iglob(search_path, recursive=True))))
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/pankaj/anaconda3/envs/w2v/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AssertionError
7139it [00:05, 1406.09it/s]
```

**Comment by harveenchadha** [comment]
Hi, 

The sample rate of the data that you are using is not 16,000. Please downsample the data.

**Comment by mirishkarganesh** [comment]
Thank you @harveenchadha ! I have resolved the bug.
