### ISSUE TITLE
error while finetuning with wav2vec_large.pt and wav2vec_small_100h.pt pretrained models

### ISSUE THREAD

**Issue by mukherjeesougata-eros** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#26]
I am trying to finetune  mini-librispeech data with wav2vec_large.pt and wav2vec_small_100h.pt pretrained models in the vakyansh-wav2vec2-experimentation(ieee branch) folder,but I am facing the following error:-
 ```Traceback (most recent call last):
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq_cli/train.py", line 95, in main
    model = task.build_model(cfg.model)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/tasks/audio_pretraining.py", line 277, in build_model
    model = super().build_model(model_cfg)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/tasks/fairseq_task.py", line 323, in build_model
    model = models.build_model(cfg, self)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/models/__init__.py", line 99, in build_model
    return model.build_model(cfg, task)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 167, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, task.target_dictionary)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 314, in __init__
    state = checkpoint_utils.load_checkpoint_to_cpu(cfg.w2v_path, arg_overrides)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/checkpoint_utils.py", line 304, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/checkpoint_utils.py", line 549, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/data/Sougata/vakyansh-wav2vec2-experimentation/wav2vec/fairseq/fairseq/dataclass/utils.py", line 366, in convert_namespace_to_omegaconf
    OmegaConf.to_container(composed_cfg, resolve=True, enum_to_str=True)
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 442, in to_container
    return BaseContainer._to_content(cfg, resolve=resolve, enum_to_str=enum_to_str)
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 195, in _to_content
    node, resolve=resolve, enum_to_str=enum_to_str
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 189, in _to_content
    throw_on_missing=False, throw_on_resolution_failure=True
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/omegaconf/base.py", line 128, in _dereference_node
    throw_on_resolution_failure=throw_on_resolution_failure,
  File "/data/anaconda3/envs/fairseq/lib/python3.7/site-packages/omegaconf/base.py", line 328, in _resolve_simple_interpolation
    f"{inter_type} interpolation key '{inter_key}' not found"
omegaconf.errors.ConfigKeyError: str interpolation key 'model.mask_min_space' not found


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.```

Kindly please help

**Comment by harveenchadha** [comment]
You need to install the particular version of fairseq as mentioned in the installation instructions.
