### ISSUE TITLE
Problem while pretraining on custom dataset

### ISSUE THREAD

**Issue by mujhenahiata** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#28]

**Comment by mujhenahiata** [comment]
user@user:/opt/vakyansh-wav2vec2-experimentation/scripts/pretraining$ bash start_pretraining_base.sh 
** Directory to code is: /opt/vakyansh-wav2vec2-experimentation
** Config path is: /opt/vakyansh-wav2vec2-experimentation/config/wav2vec2_base_librispeech.yaml
** Data path is: /opt/vakyansh-wav2vec2-experimentation/data/pretraining
** Checkpoint will be saved at: /opt/vakyansh-wav2vec2-experimentation/checkpoints/pretraining
** Logs will be saved at: /opt/vakyansh-wav2vec2-experimentation/logs/pretraining
** Update frequency is: 16Traceback (most recent call last):
  File "/user/.local/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 543, in select
    _root, _last_key, value = cfg._select_impl(
  File "/user/.local/lib/python3.8/site-packages/omegaconf/base.py", line 279, in _select_impl
    assert ret is None or isinstance(ret, Container)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/opt/vakyansh-wav2vec2-experimentation/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "/user/.local/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 100, in run
    cfg = self.compose_config(
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/user/.local/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 502, in _apply_overrides_to_config
    if OmegaConf.select(
  File "/user/.local/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 552, in select
    format_and_raise(node=cfg, key=key, value=None, cause=e, msg=str(e))
  File "/user/.local/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/user/.local/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
AssertionError: 
	full_key: task.data
	reference_type=Optional[FairseqConfig]
	object_type=FairseqConfig


i prepared the data and then ran the pretraining part.
got this error 

model type used: BASE pretraining

**Comment by harveenchadha** [comment]
Can you please provide the fairseq version you are using?

**Comment by mujhenahiata** [comment]
wasnt working on it for a while. 
i was infrencing and came across this error 

from fairseq import utils
ModuleNotFoundError: No module named 'fairseq'

this version i am using

https://github.com/Open-Speech-EkStep/fairseq -b v2-hydra

**Comment by mujhenahiata** [comment]
I was not working on it for a while, now that I have resumed I came across another problem.
there is another problem I came across, the flashlight has a separate class for processing text and it is in a seperate branch. 
how you install the flashlight library.
